/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexiones.Conexiones;
import Reportes.GenerarReportes;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Charlie
 */
public class ControlClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ControlClientes
     */
    public ControlClientes() {
        initComponents();
        verClientes();
        IdCliente.setVisible(false);
        denuevo();
        deshabilitar();
        
       
    }
    
    public void denuevo(){
    cancelar.setEnabled(false);
    nuevo.setEnabled(true);
    reporte.setEnabled(false);
    actualizar.setEnabled(false);
    editar.setEnabled(false);
    eliminar.setEnabled(false);
    } 
    public void deshabilitar(){
    TextNombre.setEnabled(false);
    TextNombre1.setEnabled(false);
    jTextField9.setEnabled(false);
    jTextField1.setEnabled(false);
    jTextField3.setEnabled(false);
    jTextField15.setEnabled(false);
    jButton3.setEnabled(false);
    
    }
    public void limpiar(){
    TextNombre.setText("");
    TextNombre1.setText("");
    jTextField9.setText("");
    jTextField1.setText("");
    jTextField3.setText("");
    jTextField15.setText("");
    }
    public void habilitar(){
    TextNombre.setEnabled(true);
    TextNombre1.setEnabled(true);
    jTextField9.setEnabled(true);
    jTextField1.setEnabled(true);
    jTextField3.setEnabled(true);
    jTextField15.setEnabled(true);
    jButton3.setEnabled(true);
    }
    
    public void vaciarTabla2(){
        DefaultTableModel modelo2 = (DefaultTableModel) jTable2.getModel();
        String titulos[] = {"ID","Nombre","Telefono","Nit","correo","Dirección fiscal","Nombre de Factura"};
        modelo2 = new DefaultTableModel(null,titulos);
         jTable2.setModel(modelo2);
    }
    
    public void verClientes(){
    vaciarTabla2();
    
     try {
            Connection con1 = null;
            DefaultTableModel miModelo = (DefaultTableModel) jTable2.getModel();
            Conexiones conect1 = new Conexiones();
            con1 = conect1.getConnection();
            String dts[] = new String[7];
            String sql = "select * from Clientes";
            Statement st = con1.createStatement();
            ResultSet rs = st.executeQuery(sql);
//            int noclientecont =0;
            while(rs.next()){
//   
//                noclientecont++;
                dts[0] = rs.getString("IdCliente");               
                dts[1] = rs.getString("NombreCliente");
                dts[2] = rs.getString("Telefono");
                dts[3] = rs.getString("Nit");
                dts[4] = rs.getString("Correo");
                dts[5] = rs.getString("DireccionFiscal");
                dts[6] = rs.getString("NombreFactura");
                this.IdCliente.setText(String.valueOf(rs.getInt("IdCliente")));
               
                miModelo.addRow(dts);
            }

            jTable2.setModel(miModelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "NO SE PUEDEN VISUALIZAR LOS CLIENTES", "Error", JOptionPane.ERROR_MESSAGE);
        }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        IdCliente = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextNombre1 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Status = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        reporte = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Control de clientes");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Datos del comprador:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        TextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNombreKeyTyped(evt);
            }
        });

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Telefono:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Nit:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Correo:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Nombre Factura:");

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel29.setText("Dirección fiscal:");

        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextNombre1))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TextNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        actualizar.setText("Guardar cambios");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        reporte.setText("Ver compras realizadas");
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });

        nuevo.setText("Nuevo Cliente");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar)
                    .addComponent(eliminar)
                    .addComponent(nuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizar)
                    .addComponent(reporte)
                    .addComponent(cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       jButton3.setEnabled(false);
        
//           int valor = JOptionPane.showConfirmDialog(this,"Se borrarán los datos del cliente actual, desea continuar?","Advertencia",JOptionPane.YES_NO_OPTION);
//            if(valor == JOptionPane.YES_OPTION){

          
        try
        {
          
            int fila = jTable2.getSelectedRow();
           
            TextNombre.setText(jTable2.getValueAt(fila, 1).toString());// cliente
            jTextField9.setText(jTable2.getValueAt(fila, 2).toString());//telefono
            jTextField1.setText (jTable2.getValueAt(fila,3).toString()); // nit
            jTextField3.setText(jTable2.getValueAt(fila, 4).toString());//correo
            jTextField15.setText(jTable2.getValueAt(fila, 5).toString());//telefono del cliente    
            TextNombre1.setText(jTable2.getValueAt(fila,6).toString());
        } catch (Exception ex)
        {
          
            Status.setText("ERROR AL SELECCIONAR UN EQUIPO : " + ex.getMessage());
            
        }
         editar.setEnabled(true);
         nuevo.setEnabled(false);
         cancelar.setEnabled(true);
         reporte.setEnabled(true);
         actualizar.setEnabled(false);
         deshabilitar();
    }//GEN-LAST:event_jTable2MouseClicked

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TextNombreActionPerformed

    private void TextNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNombreKeyPressed
        DefaultTableModel model = new DefaultTableModel();
        Statement st = null;
        ResultSet rs = null;
        Connection con2 = null;
        String titulos[] = {"ID","Nombre","Telefono","Nit","correo","Dirección fiscal"};
        String[] registros = new String[10];

        String sql = "SELECT * FROM Clientes WHERE NombreCliente LIKE '%" + TextNombre.getText().trim() + "%'";

        model = new DefaultTableModel(null, titulos);
        Conexiones conect1 = new Conexiones();
        con2 = conect1.getConnection();

        try
        {
            st = (Statement) con2.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                registros[0] = rs.getString("IdCliente");
                registros[1] = rs.getString("NombreCliente");
                registros[2] = rs.getString("Telefono");
                registros[3] = rs.getString("Nit");
                registros[4] = rs.getString("Correo");
                registros[5] = rs.getString("DireccionFiscal");

                model.addRow(registros);
            }
            jTable2.setModel(model);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
        }

    }//GEN-LAST:event_TextNombreKeyPressed

    private void TextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNombreKeyTyped
        // solo letras
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)){
            Status.setText("Ingrese Letras por favor");
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_TextNombreKeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            Status.setText("Ingrese numeros por favor");
        }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        DefaultTableModel model = new DefaultTableModel();
        Statement st = null;
        ResultSet rs = null;
        Connection con2 = null;
        String titulos[] = {"ID","Nombre","Telefono","Nit","correo","Dirección fiscal"};
        String[] registros = new String[10];

        String sql = "SELECT * FROM Clientes WHERE Nit LIKE '%" + jTextField1.getText().trim() + "%'";

        model = new DefaultTableModel(null, titulos);
        Conexiones conect1 = new Conexiones();
        con2 = conect1.getConnection();

        try
        {
            st = (Statement) con2.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                registros[0] = rs.getString("IdCliente");
                registros[1] = rs.getString("NombreCliente");
                registros[2] = rs.getString("Telefono");
                registros[3] = rs.getString("Nit");
                registros[4] = rs.getString("Correo");
                registros[5] = rs.getString("DireccionFiscal");

                model.addRow(registros);
            }
            jTable2.setModel(model);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        jButton3.setEnabled(false);
        if(TextNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta el nombre del Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
            jTextField1.requestFocus();
        }

        else{
            try{

                Connection con = null;
                Conexiones conecti = new Conexiones();
                con = conecti.getConnection();
                Statement st = con.createStatement();

                String sql = "insert into Clientes(NombreCliente,Telefono,Nit,Correo,DireccionFiscal,NombreFactura) values (?,?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, TextNombre.getText().trim());
                pst.setString(2, jTextField9.getText().trim());
                pst.setString(3, jTextField1.getText().trim());
                pst.setString(4, jTextField3.getText().trim());
                pst.setString(5, jTextField15.getText().trim());
                pst.setString(6, TextNombre1.getText().trim());

                int n = pst.executeUpdate();

                if (n > 0)
                {
                    Status.setText("CLIENTE GUARDADO CORRECTAMENTE");

                    vaciarTabla2();
                    verClientes();

                }
            }
            catch (SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, e);
                JOptionPane.showMessageDialog(this, "EL CLIENTE NO HA SIDO GUARDADO CORRECTAMENTE", "Error", JOptionPane.ERROR_MESSAGE);
            }
            denuevo();
        deshabilitar();
        

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        habilitar();
        editar.setEnabled(false);
        cancelar.setEnabled(true);
        actualizar.setEnabled(true);
        reporte.setEnabled(false);
        nuevo.setEnabled(false);
        eliminar.setEnabled(true);
    }//GEN-LAST:event_editarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
      habilitar();
     denuevo();
     nuevo.setEnabled(false);
     
      
    }//GEN-LAST:event_nuevoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        denuevo();
        deshabilitar();
        limpiar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
 if(TextNombre.getText().trim().isEmpty()){
            
             JOptionPane.showMessageDialog(this, "Falta el nombre del cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
             TextNombre.requestFocus();
 }
            else{
        try {
            
            
            Connection con = null;
                Conexiones conect = new Conexiones();
                con = conect.getConnection();
                Statement st = con.createStatement();
                String sql= "update Clientes set NombreCliente=?, Correo=?, "
                        + "Nit=?, DireccionFiscal=?, Telefono=? ,NombreFactura=? where IdCliente = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, TextNombre.getText().trim());
                pst.setString(2, jTextField3.getText().trim());
                pst.setString(3, jTextField1.getText().trim());
                pst.setString(4, jTextField15.getText().trim());
                pst.setString(5, jTextField9.getText().trim());
                pst.setString(6, TextNombre1.getText().trim());
                pst.setInt(7, Integer.parseInt(IdCliente.getText().trim()));
                int n = pst.executeUpdate();
                if (n > 0)
                {
                    Status.setText("DATOS ACTUALIZADOS CORRECTAMENTE!");
                   
                }
                
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "No se pudo actualizar","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }
        denuevo();
        deshabilitar();
        limpiar();
        vaciarTabla2();
        verClientes();
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
     
        int opc = JOptionPane.showConfirmDialog(this, "¿ESTA SEGURO QUE DESEA ELIMINAR AL CLIENTE "+TextNombre.getText()+"?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opc == JOptionPane.YES_OPTION)
            {
                try
                {
                    Connection con = null;
                    Conexiones conect = new Conexiones();
                    con = conect.getConnection();
                    Statement st = con.createStatement();
                    String sql = "delete from Clientes where IdCliente = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setInt(1, Integer.parseInt(IdCliente.getText()));
                    int n = pst.executeUpdate();
                    if (n > 0)
                    {
                        JOptionPane.showMessageDialog(this, "DATOS ELIMINADOS CORRECTAMENTE");
                        denuevo();
                        deshabilitar();
                        limpiar();
                        vaciarTabla2();
                        verClientes();
                    }
                } catch (SQLException ex)
                {
                    JOptionPane.showMessageDialog(this, "DATOS NO ELIMINADOS CORRECTAMENTE" + ex.getMessage());
                }
            }
        
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
        
        GenerarReportes rep = new GenerarReportes();
        rep.ReporteCliente(TextNombre.getText());
        
        
        
    }//GEN-LAST:event_reporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdCliente;
    private javax.swing.JLabel Status;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextNombre1;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton reporte;
    // End of variables declaration//GEN-END:variables
}
